### ISSUE TITLE
source/demo.ts:3:28 - error TS2307: Cannot find module '@keydonix/uniswap-oracle-sdk' or its corresponding type declarations. 

### ISSUE THREAD

**Issue by BoxOfCereal** [Keydonix/uniswap-oracle#10]
I am trying to run the demo by the perscribed commands in the readme. EG: `npm install`, `npm install @keydonix/uniswap-oracle-sdk` I'm not well acquainted with TS and don't know if this is a bug on my end. Thank you.

```Powershell
C:\Users\Dingu\Documents\oracle\uniswap-oracle\demo\node_modules\ts-node\src\index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
source/demo.ts:3:28 - error TS2307: Cannot find module '@keydonix/uniswap-oracle-sdk' or its corresponding type declarations.  

3 import * as OracleSdk from '@keydonix/uniswap-oracle-sdk'
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (C:\Users\Dingu\Documents\oracle\uniswap-oracle\demo\node_modules\ts-node\src\index.ts:434:12)
    at reportTSError (C:\Users\Dingu\Documents\oracle\uniswap-oracle\demo\node_modules\ts-node\src\index.ts:438:19)
    at getOutput (C:\Users\Dingu\Documents\oracle\uniswap-oracle\demo\node_modules\ts-node\src\index.ts:578:36)
    at Object.compile (C:\Users\Dingu\Documents\oracle\uniswap-oracle\demo\node_modules\ts-node\src\index.ts:775:32)
    at Module.m._compile (C:\Users\Dingu\Documents\oracle\uniswap-oracle\demo\node_modules\ts-node\src\index.ts:858:43)        
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Dingu\Documents\oracle\uniswap-oracle\demo\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ demo: `npx ts-node --project tsconfig.json source/demo.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dingu\AppData\Roaming\npm-cache\_logs\2020-08-03T01_47_52_689Z-debug.log
PS C:\Users\Dingu\Documents\oracle\uniswap-oracle\demo>

```

**Comment by MicahZoltu** [comment]
@BoxOfCereal If you want to run the demo you'll need to clone the repository and then follow the instructions in the `# Developing` section of the readme.  If you want to use the library in one of your JS projects, then you would need to do `npm install @keydonix/uniswap-oracle-sdk` and you would interact with it from a TypeScript or JavaScript application, website, etc.

Note, you will *also* need to integrate the contracts with your application if you are going this route.

If you did clone the repository and are trying to to build, make sure you first build the SDK and SDK Adapter projects in the `## Building` section of the readme, you have to build each of the projects first, with the demo being last.

**Comment by BoxOfCereal** [comment]
Ok thank you very much. I misread the instructions! I don't understand exactly how it works but it's awesome! Thanks for open sourcing it!
