### ISSUE TITLE
File Import Callback Not Supported

### ISSUE THREAD

**Issue by eerkaijun** [Keydonix/uniswap-oracle#36]
When I run `npm run build` in the demo directory, I ran into this error:

```
> @ build /home/kaijun/Documents/uniswap-oracle/demo
> npx ts-node --project scripts/tsconfig.json scripts/compile-contracts

Error: The following errors/warnings were returned by solc:

PriceEmitter.sol:4:1: ParserError: Source "@keydonix/UniswapOracle.sol" not found: File import callback not supported
import { UniswapOracle } from  "@keydonix/UniswapOracle.sol";
^-----------------------------------------------------------^

PriceEmitter.sol:5:1: ParserError: Source "@keydonix/IUniswapV2Pair.sol" not found: File import callback not supported
import { IUniswapV2Pair } from "@keydonix/IUniswapV2Pair.sol";
^------------------------------------------------------------^


    at compileContracts (/home/kaijun/Documents/uniswap-oracle/demo/scripts/compile-contracts.ts:74:10)
    at main (/home/kaijun/Documents/uniswap-oracle/demo/scripts/compile-contracts.ts:108:42)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `npx ts-node --project scripts/tsconfig.json scripts/compile-contracts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kaijun/.npm/_logs/2022-02-04T16_35_26_018Z-debug.log
```

Any ideas on the cause behind it? I've ran `npm install`.

**Comment by MicahZoltu** [comment]
Sorry for the delay in getting to this.  It should be fixed now.
